window.COMPANY_METRICS = [
  {
    "ticker": "BESI.AS",
    "name": "Besi",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 22,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": -3.0,
    "grossMargin": 63.0,
    "operatingMargin": 29.0,
    "market": "Netherlands",
    "oneLiner": "42% die-attach share + hybrid bonding pioneer. Equipment chokepoint for CPO/AI packaging. Near BUY.",
    "catalyst": "Q4 orders +105% + hybrid bonding \u20ac476M by 2026",
    "share": "42% die-attach",
    "opticsPct": 18.0,
    "thesis": "42% die-attach. Photonics bonding growing but still minority."
  },
  {
    "ticker": "0522.HK",
    "name": "ASMPT",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 21,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 10.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Hong Kong",
    "oneLiner": "AMICRA owns photonic assembly chokepoint; diversified equipment co limits pure-play upside.",
    "catalyst": "SiPh die bonding + TCB record + AI packaging",
    "share": "SiPh die bonding",
    "opticsPct": 15.0,
    "thesis": "Owns AMICRA photonic die bonder (sub-micron). Profit +164%."
  },
  {
    "ticker": "042700.KS",
    "name": "Hanmi Semi",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Korea",
    "oneLiner": "HBM-to-photonics bridge. 71% TC bonder share but SK Hynix diversifying. CPO expansion is new angle.",
    "catalyst": "HBM TC bonder 71% share + CPO packaging entry",
    "share": "71% TC bonder",
    "opticsPct": 10.0,
    "thesis": "71% TC bonder share for HBM. Expanding into CPO packaging."
  },
  {
    "ticker": "FN",
    "name": "Fabrinet",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 19.0,
    "grossMargin": 12.0,
    "operatingMargin": 11.0,
    "market": "Thailand",
    "oneLiner": "Best risk-adjusted AI photonics play; fortress balance sheet, agnostic winner",
    "catalyst": "NVIDIA sole-source 1.6T + 50% capacity expansion",
    "share": "NVIDIA sole-src",
    "opticsPct": 75.0,
    "thesis": "~75% of revenue from optical assembly. Rest is automotive/industrial."
  },
  {
    "ticker": "3450.TW",
    "name": "ELASER",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Taiwan optical manufacturing node flagged as a contract partner to both Lumentum and Coherent.",
    "catalyst": "COHR/LITE assembly read-through + SiPh / CPO industrialization",
    "share": "Optical mfg partner",
    "opticsPct": 60.0,
    "thesis": "Assembly / packaging bridge rather than a device inventor. Mapped because Taiwan trade press explicitly linked it to both Lumentum and Coherent."
  },
  {
    "ticker": "300394.SZ",
    "name": "TFC Optical",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 53.0,
    "grossMargin": 45.0,
    "operatingMargin": 41.0,
    "market": "China",
    "oneLiner": "Chinese Fabrinet: $35B cap, $662M rev. Optical sub-assembly bridge between components and modules.",
    "catalyst": "Leading Chinese OSA/packaging for transceivers",
    "share": "Chinese OSA",
    "opticsPct": 90.0,
    "thesis": "Chinese Fabrinet. $35B cap OSA packaging bridge. 45% GM, 41% OPM."
  },
  {
    "ticker": "3711.TW",
    "name": "ASE",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 12.0,
    "grossMargin": 16.0,
    "operatingMargin": 8.0,
    "market": "Taiwan",
    "oneLiner": "World #1 OSAT with dedicated SiPh packaging. CPO <5pJ/bit demo. Lightmatter 3D photonics partner.",
    "catalyst": "SiPh packaging platform + Lightmatter CPO + $300-400M SiPh rev",
    "share": "#1 OSAT",
    "opticsPct": 5.0,
    "thesis": "#1 OSAT. SiPh packaging platform. Lightmatter CPO partnership."
  },
  {
    "ticker": "AMKR",
    "name": "Amkor",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "#2 OSAT. 2.5D packaging nearly tripling in 2026. $7B US advanced packaging investment.",
    "catalyst": "2.5D 3x growth + $7B Arizona campus + photonics team",
    "share": "#2 OSAT",
    "opticsPct": 5.0,
    "thesis": "#2 OSAT. 2.5D tripling 2026. $7B Arizona campus."
  },
  {
    "ticker": "KLIC",
    "name": "K&S",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "#2 advanced packaging behind Besi. SiPh CPO bonding orders but less dominant position.",
    "catalyst": "SiPh TCB orders + CoWoS qualification",
    "share": "SiPh TCB",
    "opticsPct": 10.0,
    "thesis": "TCB orders for SiPh CPO. CoWoS qualified."
  },
  {
    "ticker": "CLS",
    "name": "Celestica",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 28.0,
    "grossMargin": 11.0,
    "operatingMargin": 8.0,
    "market": "Canada",
    "oneLiner": "Bigger Fabrinet: AI data center EMS at 0.7x sales. 55% custom Ethernet switch mfg share. Near BUY.",
    "catalyst": "FY26 $17B guide + 55% custom switch share + CCS +40%",
    "share": "55% custom sw",
    "opticsPct": 40.0,
    "thesis": "CCS ~75% of rev but includes compute + networking, not just optical."
  },
  {
    "ticker": "2317.TW",
    "name": "Foxconn",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 22.0,
    "grossMargin": 6.0,
    "operatingMargin": 3.0,
    "market": "Taiwan",
    "oneLiner": "World's largest AI server maker. $248B rev at 0.24x sales. Broad AI hardware proxy, not photonics.",
    "catalyst": "Cloud/networking 40% of rev + NVIDIA server assembly",
    "share": "$248B rev",
    "opticsPct": 5.0,
    "thesis": "World's largest AI server maker. $248B rev. Optical is tiny fraction."
  },
  {
    "ticker": "2382.TW",
    "name": "Quanta",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 108.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "#2 AI server ODM. $60B rev, NVIDIA GB200 orders for MSFT/AMZN/GOOG/META. 0.5x sales.",
    "catalyst": "AI servers 70% of server rev + GB200 orders",
    "share": "AI server #2",
    "opticsPct": 5.0,
    "thesis": "#2 AI server ODM. +108% growth. NVIDIA GB200 orders."
  },
  {
    "ticker": "3231.TW",
    "name": "Wistron",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 108.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Fastest-growing Taiwan ODM +108%. NVIDIA locked entire plant. Broad AI server proxy.",
    "catalyst": "NVIDIA booked capacity + $69B rev +108% + Blackwell/Rubin",
    "share": "AI server #3",
    "opticsPct": 5.0,
    "thesis": "#3 AI server ODM. +108%. NVIDIA booked entire plant."
  },
  {
    "ticker": "002475.SZ",
    "name": "Luxshare",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 9,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 23.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "$43B China manufacturing giant with optical transceiver ambitions; optical too small vs total rev.",
    "catalyst": "Full-stack AI DC + optical 10G-1.6T + OpenAI supplier",
    "share": "OpenAI supplier",
    "opticsPct": 5.0,
    "thesis": "$43B conglomerate. OpenAI supplier. Optical 10G-1.6T."
  },
  {
    "ticker": "CRDO",
    "name": "Credo",
    "segment": "Components & Connectivity",
    "verdict": "BUY",
    "chokepointScore": 23,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 202.0,
    "grossMargin": 69.0,
    "operatingMargin": 45.0,
    "market": "US",
    "oneLiner": "88% AEC monopoly, 68% GM, 200% growth, pulled back from $214; 67% customer concentration risk",
    "catalyst": "53% pullback + 1.6T Bluebird DSP + 200G AEC",
    "share": "88% AEC | SOLE SOURCE",
    "opticsPct": 95.0,
    "thesis": "88% AEC. Nearly all revenue from DC connectivity."
  },
  {
    "ticker": "AVGO",
    "name": "Broadcom",
    "segment": "Components & Connectivity",
    "verdict": "BUY",
    "chokepointScore": 22,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 29.0,
    "grossMargin": 76.0,
    "operatingMargin": 45.0,
    "market": "US",
    "oneLiner": "Gorilla of AI networking; Tomahawk monopoly + XPU + optical DSP + SiPh. 68% EBITDA. $1.53T.",
    "catalyst": "AI rev +106% to $40.4B + $162B backlog + Taurus DSP",
    "share": "~90% switch ASIC (eroding)",
    "opticsPct": 15.0,
    "thesis": "Optical DSP + SiPh is ~15% of semi rev. Rest is XPU, software, etc."
  },
  {
    "ticker": "LITE",
    "name": "Lumentum",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 21,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 65.0,
    "grossMargin": 43.0,
    "operatingMargin": 31.0,
    "market": "US",
    "oneLiner": "Laser chip king of AI optics; dominant but priced for perfection at 62x fwd P/E",
    "catalyst": "NVIDIA $2B deal + $8B revenue target",
    "share": "50-60% EML",
    "opticsPct": 95.0,
    "thesis": "50-60% high-end EML. NVIDIA $2B. Nearly pure-play optical."
  },
  {
    "ticker": "6503.T",
    "name": "Mitsubishi",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 5.0,
    "grossMargin": 31.0,
    "operatingMargin": 10.0,
    "market": "Japan",
    "oneLiner": "50% global EML share but buried in \u00a55.5T conglomerate; Lumentum better for EML exposure",
    "catalyst": "3x optical capacity by FY28",
    "share": "50% EML",
    "opticsPct": 3.0,
    "thesis": "50% total EML volume but EML is tiny part of JPY5.5T conglomerate."
  },
  {
    "ticker": "6777.T",
    "name": "Santec",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "Japan micro-cap optical component niche. Tunable filters/WSS inside every coherent transceiver.",
    "catalyst": "CPO tunable laser + MEMS tunable filters for 400G+",
    "share": "Tunable filters + WSS",
    "opticsPct": 85.0,
    "thesis": "Niche optical filter, WSS, and tunable laser specialist with CPO-relevant components."
  },
  {
    "ticker": "MTSI",
    "name": "MACOM",
    "segment": "Components & Connectivity",
    "verdict": "BUY",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 33.0,
    "grossMargin": 57.0,
    "operatingMargin": 25.0,
    "market": "US",
    "oneLiner": "Best under-discovered AI photonics name; 57% gross margins, analog IC moat, data center +48%",
    "catalyst": "Raised growth to 35-40% + 1.6T component ramp",
    "share": "57% GM, DC+48%",
    "opticsPct": 30.0,
    "thesis": "Data center ~30% of rev. Rest is defense + telecom."
  },
  {
    "ticker": "5802.T",
    "name": "Sumitomo Elec",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 5.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "Japan conglomerate with EML/fiber exposure; not a pure play but cheap at 13-15x P/E",
    "catalyst": "EML demand + fiber buildout",
    "share": "Major EML",
    "opticsPct": 3.0,
    "thesis": "Japan conglomerate with EML/CW-LD lasers and optical fiber."
  },
  {
    "ticker": "MRVL",
    "name": "Marvell",
    "segment": "Components & Connectivity",
    "verdict": "BUY",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 76.0,
    "grossMargin": 60.0,
    "operatingMargin": 36.0,
    "market": "US",
    "oneLiner": "Boldest photonic bet in semis; $3.25B Celestial AI + 50+ custom AI programs. $116 consensus.",
    "catalyst": "Celestial AI + 1.6T Ara DSP + custom silicon ramp",
    "share": "$3.25B Celestial",
    "opticsPct": 25.0,
    "thesis": "Optical DSP ~25% of DC rev. Rest is custom silicon, storage, networking."
  },
  {
    "ticker": "SMTC",
    "name": "Semtech",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 16.0,
    "grossMargin": 58.0,
    "operatingMargin": 19.0,
    "market": "US",
    "oneLiner": "Under-discovered LPO disruptor. Removing DSP from optical modules. Hyperscaler LPO design wins.",
    "catalyst": "LPO disruption + FiberEdge TIA + CopperEdge ACC + DC +50%",
    "share": "LPO architecture",
    "opticsPct": 20.0,
    "thesis": "Signal integrity (optical TIA/CDR) ~20%. Rest is LoRa IoT."
  },
  {
    "ticker": "4991.TW",
    "name": "GCS Holdings",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 27.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Taiwan optical component maker targeting SiPh/CPO. Both TX and RX components. 2026 mass production.",
    "catalyst": "200G PD + CW laser ramp for SiPh + CPO",
    "share": "200G PD + CW lasers",
    "opticsPct": 90.0,
    "thesis": "Taiwan optical component supplier targeting 200G photodiodes and CW lasers for SiPh transceivers."
  },
  {
    "ticker": "6442.TW",
    "name": "EZconn",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 64.0,
    "grossMargin": 49.0,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Optical active/passive components and module supplier. 2025 growth is real, but the layer remains competitive.",
    "catalyst": "Optical business dominance + 400G/800G datacom ramp + IntelliEPI CPO tie-up",
    "share": "~92% optical comms mix",
    "opticsPct": 92.0,
    "thesis": "Taiwan optical components and module supplier. Optical communication was ~92% of 2024 revenue and datacenter products now include 400G/800G offerings."
  },
  {
    "ticker": "MXL",
    "name": "MaxLinear",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": -7.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "Small-cap optical DSP turnaround. Right products but smallest competitor. Watch OFC 2026 wins.",
    "catalyst": "Rushmore 1.6T DSP + Annapurna 224G retimer",
    "share": "1.6T DSP",
    "opticsPct": 20.0,
    "thesis": "Small-cap 1.6T Rushmore DSP turnaround. Annapurna retimer."
  },
  {
    "ticker": "SIVE.ST",
    "name": "Sivers Semi",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 25.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Sweden",
    "oneLiner": "InP DFB laser micro-cap; real tech, credible partners, but pre-profit and pre-scale",
    "catalyst": "POET demos + O-Net ELS + LiDAR ramp Q4",
    "share": "InP DFB lasers",
    "opticsPct": 80.0,
    "thesis": "InP DFB laser micro-cap. POET + O-Net + Enablence CPO partnerships. SEK304M rev (+25%). Pre-profit but 80% photonics pure-play. LiDAR ramp Q4 2026."
  },
  {
    "ticker": "IPGP",
    "name": "IPG Photonics",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 9,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 3.0,
    "grossMargin": 36.1,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "Industrial fiber laser leader but wrong market; no AI data center exposure",
    "catalyst": "Defense laser pivot + cyclical recovery",
    "share": "Industrial laser leader",
    "opticsPct": 15.0,
    "thesis": "Fiber-laser leader with limited AI data-center exposure and mostly industrial end-markets."
  },
  {
    "ticker": "LASR",
    "name": "nLIGHT",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 9,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 32.0,
    "grossMargin": 30.0,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "Defense laser co riding AI hype; no data center revenue to justify 13x sales valuation",
    "catalyst": "Defense laser strength + AI photonics narrative",
    "share": "Defense lasers",
    "opticsPct": 20.0,
    "thesis": "Defense-weighted laser company with an aspirational rather than proven AI photonics angle."
  },
  {
    "ticker": "ASML",
    "name": "ASML",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 25,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 30.0,
    "grossMargin": 51.0,
    "operatingMargin": 35.0,
    "market": "Netherlands",
    "oneLiner": "Lithography monopoly. Every SiPh foundry expansion needs ASML DUV tools. $320B+ market cap context.",
    "catalyst": "DUV lithography monopoly for SiPh + every new fab needs ASML",
    "share": "100% litho | SOLE SOURCE",
    "opticsPct": 5.0,
    "thesis": "Only lithography supplier. SiPh uses DUV but is tiny fraction of total."
  },
  {
    "ticker": "6146.T",
    "name": "Disco",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 23,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 28.0,
    "grossMargin": 50.0,
    "operatingMargin": 39.0,
    "market": "Japan",
    "oneLiner": "75% global dicing monopoly. 39% OPM. Every chip (including SiPh) needs Disco. Japanese hidden gem.",
    "catalyst": "AI chip volume + SiPh dicing + consumables recurring",
    "share": "75% dicing",
    "opticsPct": 12.0,
    "thesis": "75% dicing. SiPh is small fraction of all chip dicing volumes."
  },
  {
    "ticker": "AIXA.DE",
    "name": "Aixtron",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 21,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": -1.0,
    "grossMargin": 43.0,
    "operatingMargin": 15.0,
    "market": "Germany",
    "oneLiner": "Dominant MOCVD duopoly partner. \"Most underappreciated AI beneficiary.\" FY26 flat on SiC headwinds.",
    "catalyst": "70-90% MOCVD share + optoelectronics growth for AI",
    "share": "70-90% MOCVD",
    "opticsPct": 30.0,
    "thesis": "70-90% MOCVD. Every InP/GaAs laser chip needs Aixtron."
  },
  {
    "ticker": "VECO",
    "name": "Veeco",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 21,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": -7.0,
    "grossMargin": 41.0,
    "operatingMargin": 13.0,
    "market": "US",
    "oneLiner": "MOCVD equipment leader; grows every InP/GaAs laser chip. Duopoly with Aixtron. Merging with Axcelis.",
    "catalyst": "MOCVD duopoly + Lumina+ for photonics + Axcelis merger",
    "share": "MOCVD #2",
    "opticsPct": 20.0,
    "thesis": "MOCVD duopoly #2. Lumina+ for photonics. Merging with Axcelis."
  },
  {
    "ticker": "AMAT",
    "name": "Applied Materials",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "#1 semi equipment co. Deposition essential for all SiPh manufacturing. Photonics is tiny fraction.",
    "catalyst": "GF Singapore photonics fab + deposition tools in every SiPh fab",
    "share": "Core SiPh deposition tools",
    "opticsPct": 5.0,
    "thesis": "Largest semiconductor equipment vendor with direct relevance to SiPh deposition and the GF photonics line."
  },
  {
    "ticker": "LRCX",
    "name": "Lam Research",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "#2 semi equipment. Etch tools define optical structures in every SiPh chip. Photonics tiny fraction.",
    "catalyst": "Etch tools for SiPh waveguide patterning",
    "share": "Core SiPh etch tools",
    "opticsPct": 5.0,
    "thesis": "Critical etch and deposition tool supplier for SiPh waveguide fabrication."
  },
  {
    "ticker": "JEN.DE",
    "name": "Jenoptik",
    "segment": "Equipment",
    "verdict": "AVOID",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": -6.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Germany",
    "oneLiner": "German photonics co with \u20ac1.05B rev (-6%). Weak semi cycle. Not directly AI DC-focused.",
    "catalyst": "Semi equipment photonics + industrial optical",
    "share": "~60% photonics",
    "opticsPct": 60.0,
    "thesis": "European photonics and semiconductor-equipment exposure, but only indirect AI photonics relevance."
  },
  {
    "ticker": "APH",
    "name": "Amphenol",
    "segment": "Fiber & Connectors",
    "verdict": "BUY",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 52.0,
    "grossMargin": 33.0,
    "operatingMargin": 28.0,
    "market": "US",
    "oneLiner": "Dominant AI data center connector company. $23.1B rev, 27.5% OPM record. Every rack uses Amphenol.",
    "catalyst": "Comms +78% + CommScope CCS $4.1B + 33% AI DC share",
    "share": "33% AI DC conn",
    "opticsPct": 15.0,
    "thesis": "Comms Solutions $3.4B of $23B. Rest is auto, defense, industrial."
  },
  {
    "ticker": "5803.T",
    "name": "Fujikura",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 20.0,
    "grossMargin": 27.0,
    "operatingMargin": 15.0,
    "market": "Japan",
    "oneLiner": "Japanese Corning; +160% in 2025 on AI fiber. Near ATH, well-priced. Strong Buy consensus.",
    "catalyst": "3x US fiber output + AI demand",
    "share": "Japan fiber",
    "opticsPct": 40.0,
    "thesis": "Japanese Corning. +160% in 2025. 3x US fiber output."
  },
  {
    "ticker": "6869.HK",
    "name": "YOFC",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "China #1, global #2 fiber cable. Hollow-core fiber innovation. Dual-listed HK+Shanghai.",
    "catalyst": "HollowBand HCF + AI x Fibre vision",
    "share": "China #1 fiber",
    "opticsPct": 35.0,
    "thesis": "China #1 / global #2 fiber. HollowBand hollow-core fiber."
  },
  {
    "ticker": "GLW",
    "name": "Corning",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 35.0,
    "grossMargin": 42.0,
    "operatingMargin": 20.0,
    "market": "US",
    "oneLiner": "Fiber infrastructure backbone of AI; $6.3B optical rev, $1B profit. Near ATH, wait for pullback.",
    "catalyst": "Meta $6B deal + $10.3B scale-out by 2030 + optical +35%",
    "share": ">50% NA fiber",
    "opticsPct": 45.0,
    "thesis": "Optical Comms $6.3B of ~$14B total. Rest is display, specialty glass."
  },
  {
    "ticker": "600487.SS",
    "name": "Hengtong",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 20.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "China #2 fiber + unique optical module packaging angle. Shanghai-listed.",
    "catalyst": "Fiber + optical packaging + CPO + liquid cooling",
    "share": "China #2 fiber",
    "opticsPct": 30.0,
    "thesis": "China #2 fiber + optical module packaging + liquid cooling."
  },
  {
    "ticker": "PRY.MI",
    "name": "Prysmian",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 5.0,
    "grossMargin": 14.0,
    "operatingMargin": 10.0,
    "market": "Italy",
    "oneLiner": "World's largest cable co. HCF 50% faster than conventional fiber. Long-term AI DC option.",
    "catalyst": "Hollow-core fiber + Relativity Networks partnership",
    "share": "HCF 50% faster",
    "opticsPct": 10.0,
    "thesis": "Fiber is ~10%. Primarily a power cable company (EUR15B)."
  },
  {
    "ticker": "STLTECH.NS",
    "name": "Sterlite",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "India",
    "oneLiner": "India's leading optical fiber co. $968M cap, $486M rev. Optical interconnect growing at 30% margins.",
    "catalyst": "Optical interconnect +53% + DC fiber 76% CAGR",
    "share": "India fiber",
    "opticsPct": 50.0,
    "thesis": "India's leading optical fiber co. Optical interconnect +53%."
  },
  {
    "ticker": "TSEM",
    "name": "Tower Semi",
    "segment": "Foundry & Platforms",
    "verdict": "BUY",
    "chokepointScore": 23,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 14.0,
    "grossMargin": 23.0,
    "operatingMargin": 12.0,
    "market": "Israel/US",
    "oneLiner": "85% SiPh foundry share; TSMC of photonics. $920M expansion 70%+ reserved. Soitec sole supplier.",
    "catalyst": "5x SiPh capacity + NVIDIA collab + margin expansion",
    "share": "85% SiPh (eroding)",
    "opticsPct": 15.0,
    "thesis": "85% SiPh foundry. SiPh $228M of $1.57B (15%). 5x expansion \u2192 35%+ by 2028."
  },
  {
    "ticker": "3105.TW",
    "name": "WIN Semi",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": -5.0,
    "grossMargin": 24.0,
    "operatingMargin": 4.0,
    "market": "Taiwan",
    "oneLiner": "World's largest GaAs foundry. VCSELs for DC optical. Pivoting from mobile to AI. Taiwan-listed.",
    "catalyst": "GaAs foundry 50%+ share + AI/optical pivot",
    "share": "50%+ GaAs",
    "opticsPct": 30.0,
    "thesis": "50%+ GaAs foundry. ~30% is optical/VCSEL, rest is RF/mobile."
  },
  {
    "ticker": "GFS",
    "name": "GlobalFoundries",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 0.0,
    "grossMargin": 28.0,
    "operatingMargin": 14.0,
    "market": "US",
    "oneLiner": "#2 SiPh foundry; $200M\u2192$1B SiPh target but legacy foundry drag. Cheap at 3.8x sales.",
    "catalyst": "SiPh doubling + AMF + China-free supply chain",
    "share": "#2 SiPh",
    "opticsPct": 3.0,
    "thesis": "#2 SiPh. $200M SiPh of ~$6.5B total. Growing to $1B by decade-end."
  },
  {
    "ticker": "INTC",
    "name": "Intel",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "SiPh technology pioneer but company in crisis. Best-in-class OCI chiplet at 5pJ/bit. Wait for turnaround.",
    "catalyst": "OCI chiplet pioneer + 8M PICs shipped",
    "share": "8M+ PICs shipped",
    "opticsPct": 5.0,
    "thesis": "Silicon photonics pioneer with OCI chiplets, but the optical story is buried inside a broader corporate restructuring."
  },
  {
    "ticker": "UMC",
    "name": "UMC",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Taiwan #2 foundry entering SiPh. 3rd major foundry option vs Tower/GF. Long-term diversification play.",
    "catalyst": "imec iSiPP300 SiPh license + risk production 2026-27",
    "share": "SiPh new entrant",
    "opticsPct": 2.0,
    "thesis": "Entering SiPh via imec iSiPP300 license. Risk production 2026-27."
  },
  {
    "ticker": "STM",
    "name": "STMicro",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "EU",
    "oneLiner": "5th SiPh foundry entrant. PIC100 for 800G/1.6T. Quadrupling capacity. Diversified $13B semi co.",
    "catalyst": "PIC100 SiPh in HV production + 4x capacity by 2027",
    "share": "PIC100",
    "opticsPct": 3.0,
    "thesis": "PIC100 SiPh in HV production. 4x capacity by 2027."
  },
  {
    "ticker": "XFAB.PA",
    "name": "X-FAB",
    "segment": "Foundry & Platforms",
    "verdict": "HOLD",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "France",
    "oneLiner": "European SiPh foundry with InP hetero integration (>120GHz). Early stage, production 2027. Niche.",
    "catalyst": "InP-on-Silicon heterogeneous integration + SiN photonics",
    "share": "InP hetero",
    "opticsPct": 5.0,
    "thesis": "European SiPh with InP heterogeneous integration (>120GHz)."
  },
  {
    "ticker": "SOI.PA",
    "name": "Soitec",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 23,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 11.0,
    "grossMargin": 32.0,
    "operatingMargin": 15.0,
    "market": "France",
    "oneLiner": "Hidden photonics monopoly at 2.7x sales; 70% SOI share but mobile weakness masks story",
    "catalyst": "Tower 5x SiPh expansion + photonics-SOI \u20ac100M+",
    "share": "70% SOI | SOLE SOURCE",
    "opticsPct": 12.0,
    "thesis": "ONLY volume photonics-SOI supplier for Tower/GF/TSMC. Photonics-SOI ~EUR100M of EUR891M. Growing fast."
  },
  {
    "ticker": "4971.TW",
    "name": "IntelliEPI",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 54.0,
    "grossMargin": 23.0,
    "operatingMargin": 13.0,
    "market": "Taiwan",
    "oneLiner": "Taiwan III-V epi specialist with APD breadcrumbs tying it to both Lumentum and Coherent.",
    "catalyst": "COHR/LITE APD epi outsourcing + EZconn CPO path",
    "share": "APD epi outsourcing",
    "opticsPct": 90.0,
    "thesis": "MBE-led InP platform with PIN/APD wafers for optical communications and data centers; Taiwan press now suggests direct APD-related outsourcing links with both Lumentum and Coherent."
  },
  {
    "ticker": "2455.TW",
    "name": "VPEC",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Closest thing to a current production choke point in III-V epi; direct AI optical demand visibility.",
    "catalyst": "AI data-center optical visibility + SiPh-linked optical growth",
    "share": "Current production ramp",
    "opticsPct": 55.0,
    "thesis": "III-V epi platform spanning HBT, VCSEL, EEL, and FP/DFB lasers. Public read-through is that AI data-center optical demand is already visible in orders."
  },
  {
    "ticker": "3081.TW",
    "name": "LandMark Optoelectronics",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 82.0,
    "grossMargin": 40.0,
    "operatingMargin": null,
    "market": "Taiwan",
    "oneLiner": "Taiwan III-V epiwafer supplier for lasers and photodetectors. Real AI-photonics exposure, but not a sole-source bottleneck.",
    "catalyst": "Taiwan photonics demand inflection + 400G/800G/1.6T epiwafer exposure",
    "share": "76.2% 2025 growth",
    "opticsPct": 90.0,
    "thesis": "Taiwan III-V epi supplier for InP/GaAs laser and photodetector wafers used in 400G/800G/1.6T optical modules."
  },
  {
    "ticker": "AXTI",
    "name": "AXT",
    "segment": "Materials & Substrates",
    "verdict": "AVOID",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": -11.0,
    "grossMargin": 13.0,
    "operatingMargin": -24.0,
    "market": "US/China",
    "oneLiner": "Owns 60-70% of InP substrate bottleneck but China mfg risk + unprofitable + extreme volatility",
    "catalyst": "InP capacity expansion July 2026",
    "share": "60-70% InP",
    "opticsPct": 80.0,
    "thesis": "60-70% InP substrates. Mostly optical end-markets. Beijing mfg risk."
  },
  {
    "ticker": "5016.T",
    "name": "JX Metals",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 15.0,
    "grossMargin": 23.0,
    "operatingMargin": 7.0,
    "market": "Japan",
    "oneLiner": "JX Advanced Metals: Japan's largest IPO since SoftBank. 40yr InP expertise. Non-China AXT alternative.",
    "catalyst": "Newly IPO'd InP substrate + 50% capacity expansion + non-China",
    "share": "40yr InP exp",
    "opticsPct": 8.0,
    "thesis": "IPO'd Mar 2025. Rev JPY775B TTM, 23% GM. Raised FY25 guidance on AI demand. InP small but strategic."
  },
  {
    "ticker": "IQE.L",
    "name": "IQE",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": -31.0,
    "grossMargin": 13.0,
    "operatingMargin": null,
    "market": "UK",
    "oneLiner": "Global epi platform with Tier 1 AI / hyperscale wins and 6-inch SiPh capability, but margins still need to recover.",
    "catalyst": "Tier 1 AI / hyperscale wins + 6-inch SiPh platform + utilization recovery",
    "share": "Tier 1 AI wins",
    "opticsPct": 70.0,
    "thesis": "Global compound-semi platform spanning InP datacom for AI plus 6-inch silicon photonics services. Platform value is ahead of current earnings."
  },
  {
    "ticker": "300308.SZ",
    "name": "Innolight",
    "segment": "Modules & Transceivers",
    "verdict": "BUY",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 60.0,
    "grossMargin": 43.0,
    "operatingMargin": 28.0,
    "market": "China",
    "oneLiner": "World's largest transceiver co; 50%+ NVIDIA share, 43% GM, 28% net margin. Geopolitical risk.",
    "catalyst": "1.6T 5x demand ramp + NVIDIA/Google dominance",
    "share": "50%+ NVIDIA",
    "opticsPct": 95.0,
    "thesis": "Pure-play optical transceivers. Nearly all revenue from DC optics."
  },
  {
    "ticker": "300502.SZ",
    "name": "Eoptolink",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 222.0,
    "grossMargin": 50.0,
    "operatingMargin": 45.0,
    "market": "China",
    "oneLiner": "#2 Chinese transceiver co; +179% growth but $50B at 22x sales is steep vs Innolight",
    "catalyst": "800G/1.6T ramp + NVIDIA #2 supplier",
    "share": "NVIDIA #2",
    "opticsPct": 95.0,
    "thesis": "China #2 transceiver. +222% growth. 50% GM, 45% OPM."
  },
  {
    "ticker": "COHR",
    "name": "Coherent",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 17.0,
    "grossMargin": 39.0,
    "operatingMargin": 5.0,
    "market": "US",
    "oneLiner": "Best photonics portfolio for AI but priced beyond consensus; wait for pullback",
    "catalyst": "1.6T ramp + NVIDIA partnership",
    "share": "$6.3B TTM",
    "opticsPct": 58.0,
    "thesis": "Networking ~58% of rev. Rest is lasers + materials."
  },
  {
    "ticker": "000936.SZ",
    "name": "Huaxicun",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "Owns Source Photonics (top-10 global transceiver). $850M cap. Opaque conglomerate structure.",
    "catalyst": "Source Photonics ownership + optical transceivers",
    "share": "Source Photonics",
    "opticsPct": 60.0,
    "thesis": "Owns Source Photonics (top-10 global transceiver)."
  },
  {
    "ticker": "002281.SZ",
    "name": "Accelink",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 37.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "China #3 optical component co; broad portfolio but lacks NVIDIA/hyperscaler AI relationships.",
    "catalyst": "Chinese telecom + DC optical components",
    "share": "China #3",
    "opticsPct": 80.0,
    "thesis": "China #3 optical component co. Broad portfolio but lacks NVIDIA relationships."
  },
  {
    "ticker": "300548.SZ",
    "name": "Broadex",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "Mid-tier Chinese optical component co. $2.68B cap, $274M rev. SiPh capability. Below Big 3.",
    "catalyst": "SiPh + PLC + transceiver packaging",
    "share": "SiPh components",
    "opticsPct": 80.0,
    "thesis": "Mid-tier Chinese optical component co with SiPh capability."
  },
  {
    "ticker": "000988.SZ",
    "name": "Huagong Tech",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 23.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "China's first laser IPO. CNY 9B rev +23%. Optical comms division testing 1.6T with leading clients.",
    "catalyst": "400G-1.6T transceivers + laser equipment + SiPh",
    "share": "Laser + optical",
    "opticsPct": 20.0,
    "thesis": "China's first laser IPO. Testing 400G-1.6T transceivers."
  },
  {
    "ticker": "AAOI",
    "name": "AAOI",
    "segment": "Modules & Transceivers",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 83.0,
    "grossMargin": 31.0,
    "operatingMargin": -12.0,
    "market": "US",
    "oneLiner": "Under-discovered AI optics dark horse; US mfg moat, zero debt, but still unprofitable",
    "catalyst": "$200M+ 1.6T order + 3.5x DC rev growth",
    "share": "US manufacturing",
    "opticsPct": 85.0,
    "thesis": "Primarily optical transceivers + CATV optical products."
  },
  {
    "ticker": "POET",
    "name": "POET Technologies",
    "segment": "Modules & Transceivers",
    "verdict": "AVOID",
    "chokepointScore": 9,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Canada / Singapore",
    "oneLiner": "Interesting tech but pre-revenue with extreme execution risk; revisit at >$10M quarterly rev",
    "catalyst": "Prototype demos H1 2026 + CPO optionality",
    "share": "Optical interposer",
    "opticsPct": 95.0,
    "thesis": "Pre-revenue optical interposer platform with high upside if wafer-level photonic integration scales."
  },
  {
    "ticker": "ANET",
    "name": "Arista",
    "segment": "Networking & Systems",
    "verdict": "BUY",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 29.0,
    "grossMargin": 64.0,
    "operatingMargin": 43.0,
    "market": "US",
    "oneLiner": "Demand signal for all photonics; 64% GM, 43% OPM, $10.7B net cash, $4.25B FCF. Franchise.",
    "catalyst": "AI rev +100% to $3.25B + 800G leadership",
    "share": "40%+ 800G",
    "opticsPct": 15.0,
    "thesis": "Consumes transceivers but is a switch company. Optical is cost input not revenue."
  },
  {
    "ticker": "2408.TW",
    "name": "Nanya Technology",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 6,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 71.0,
    "grossMargin": 18.5,
    "operatingMargin": 6.0,
    "market": "Taiwan",
    "oneLiner": "DRAM recovery name, not a photonics chokepoint. Included as article context rather than a core optical thesis.",
    "catalyst": "DRAM recovery + server-memory demand",
    "share": "DRAM cycle recovery",
    "opticsPct": 0.0,
    "thesis": "Taiwan DRAM manufacturer with AI-server demand relevance, but outside the optical interconnect value chain."
  },
  {
    "ticker": "CIEN",
    "name": "Ciena",
    "segment": "Networking & Systems",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 19.0,
    "grossMargin": 42.0,
    "operatingMargin": 8.0,
    "market": "US",
    "oneLiner": "Optical networking leader with $7.8B orders; wait for margin proof or pullback",
    "catalyst": "WL6e ramp + $5B backlog + margin expansion to 17%",
    "share": "$5B backlog",
    "opticsPct": 90.0,
    "thesis": "Nearly pure-play optical networking. ~90% from optical systems."
  },
  {
    "ticker": "CSCO",
    "name": "Cisco",
    "segment": "Networking & Systems",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 7.0,
    "grossMargin": 64.0,
    "operatingMargin": 30.0,
    "market": "US",
    "oneLiner": "Sleeping AI optics giant; $1.2B+ AI optics but diluted by $250B enterprise. Acacia ~50% coherent share.",
    "catalyst": "$5B AI orders + Acacia coherent + Silicon One G300",
    "share": "Acacia ~50%",
    "opticsPct": 5.0,
    "thesis": "Acacia optical is ~5% of $60B+ total. Enterprise/security dominant."
  },
  {
    "ticker": "NOK",
    "name": "Nokia",
    "segment": "Networking & Systems",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 3.0,
    "grossMargin": 45.0,
    "operatingMargin": 10.0,
    "market": "Finland",
    "oneLiner": "Ciena competitor ~20% optical share. InP + SiPh coherent. Telecom conglomerate dilution.",
    "catalyst": "\u20ac3.4B optical + Infinera InP + 70% TCO reduction",
    "share": "~20% optical",
    "opticsPct": 17.0,
    "thesis": "Ciena competitor. Infinera InP + Nokia SiPh. ~20% optical."
  },
  {
    "ticker": "VNP.TO",
    "name": "5N Plus",
    "segment": "Raw Materials",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 35.0,
    "grossMargin": 34.0,
    "operatingMargin": 24.0,
    "market": "Canada",
    "oneLiner": "Deepest upstream: ultra-high-purity In/Ga/Ge supplier. $391M rev +35%. +322% stock. Solar-focused.",
    "catalyst": "Germanium grant + raw metals for photonics",
    "share": "$391M rev (+35%)",
    "opticsPct": 30.0,
    "thesis": "Refines In/Ga/Ge for all compound semi. Rest is solar/other."
  },
  {
    "ticker": "5714.T",
    "name": "Dowa Holdings",
    "segment": "Raw Materials",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": -5.0,
    "grossMargin": 12.8,
    "operatingMargin": 4.7,
    "market": "Japan",
    "oneLiner": "Japan's largest indium refiner and top high-purity gallium producer. Useful geopolitical hedge, not a pricing-power moat.",
    "catalyst": "China indium export controls + non-China source",
    "share": "Japan indium leader",
    "opticsPct": 5.0,
    "thesis": "Deep-upstream indium and gallium exposure relevant to InP photonics, but commodity economics and conglomerate mix dilute the stock expression."
  },
  {
    "ticker": "4973.T",
    "name": "Japan Pure Chem",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": 11.0,
    "market": "Japan",
    "oneLiner": "Hidden monopoly: 50% global gold plating share, 2.1x sales, 4.17% yield. 52 employees. Niche but real.",
    "catalyst": "Transceiver volume explosion \u2192 gold plating demand",
    "share": "50% gold plating",
    "opticsPct": 40.0,
    "thesis": "52-employee co. 50% gold plating share. 4.17% yield."
  },
  {
    "ticker": "6857.T",
    "name": "Advantest",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 37.0,
    "grossMargin": 60.0,
    "operatingMargin": 42.0,
    "market": "Japan",
    "oneLiner": "ASML of testing. \u00a51.07T revenue. V93000 extended to SiPh/CPO testing via FormFactor. Near BUY.",
    "catalyst": "V93000 SiPh + AI chip test + 30-40% growth + multiple raises",
    "share": "ATE duopoly",
    "opticsPct": 10.0,
    "thesis": "ASML of testing. V93000 SiPh/CPO test. 60% GM, 42% OPM."
  },
  {
    "ticker": "KEYS",
    "name": "Keysight Technologies",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 23.0,
    "grossMargin": 62.0,
    "operatingMargin": 16.3,
    "market": "US",
    "oneLiner": "Dominant optical R&D and design-validation test platform. Every 1.6T transceiver lab touches Keysight-class gear.",
    "catalyst": "Wireline > wireless + 1.6T validation cycle + FY26 raise",
    "share": "Optical R&D test leader",
    "opticsPct": 18.0,
    "thesis": "The design-validation choke point in optical test. Not pure-play photonics, but one of the strongest beneficiaries of 800G/1.6T qualification cycles."
  },
  {
    "ticker": "TER",
    "name": "Teradyne",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 19,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 13.0,
    "grossMargin": 58.0,
    "operatingMargin": 24.0,
    "market": "US",
    "oneLiner": "ATE duopoly #2. Acquired PIC testing leader. AI drives 70% of revenue. $3.19B rev. Near BUY.",
    "catalyst": "Quantifi Photonics acquisition + AI 70% of rev + compute +90%",
    "share": "ATE #2",
    "opticsPct": 5.0,
    "thesis": "ATE #2. Acquired Quantifi Photonics for PIC testing."
  },
  {
    "ticker": "AEHR",
    "name": "Aehr Test Systems",
    "segment": "Test & Infrastructure",
    "verdict": "AVOID",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": 29.8,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "Niche SiPh wafer burn-in leader but $880M cap on $40M rev, unprofitable, declining margins.",
    "catalyst": "SiPh burn-in orders + AI optical I/O",
    "share": "SiPh WLBI",
    "opticsPct": 35.0,
    "thesis": "Wafer-level burn-in specialist for silicon photonics and AI optical I/O testing."
  },
  {
    "ticker": "FORM",
    "name": "FormFactor",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "SiPh wafer test infrastructure play. Keystone adds optical probing. Path to $850M revenue.",
    "catalyst": "Keystone SiPh acquisition + $850M target model",
    "share": "SiPh probe",
    "opticsPct": 15.0,
    "thesis": "SiPh wafer test via Keystone Photonics acquisition."
  },
  {
    "ticker": "HUBN.SW",
    "name": "Huber+Suhner",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": -3.0,
    "grossMargin": 38.0,
    "operatingMargin": 11.0,
    "market": "Switzerland",
    "oneLiner": "Swiss co owns leading OCS technology. $2.5B market emerging. Diversified dilution but early-mover.",
    "catalyst": "Polatis OCS leader + OCS market \u2192 $2.5B by 2029",
    "share": "OCS leader",
    "opticsPct": 15.0,
    "thesis": "Polatis OCS leader. Market $2.5B by 2029."
  },
  {
    "ticker": "AEIS",
    "name": "Adv Energy",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 21.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "Dual AI exposure: powers chip manufacturing + data centers. $1.80B rev, DC +107%. BofA pick.",
    "catalyst": "DC Computing +107% + semi equipment power",
    "share": "DC power",
    "opticsPct": 5.0,
    "thesis": "Precision power for semi equipment + AI data centers. DC +107%."
  },
  {
    "ticker": "VRT",
    "name": "Vertiv",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 28.0,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "AI DC cooling/power backbone. Not photonics directly but demand confirmation. +62% YTD 2026.",
    "catalyst": "$15B backlog + NVIDIA cooling partner + orders +252%",
    "share": "$15B backlog",
    "opticsPct": 0.0,
    "thesis": "$15B backlog. NVIDIA cooling partner. +252% orders."
  },
  {
    "ticker": "MKSI",
    "name": "MKS Instruments",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 10.5,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "United States",
    "oneLiner": "Indirect AI photonics via semi equipment; reasonable value but not a targeted play",
    "catalyst": "Semi capex cycle + Photonics division",
    "share": "Photonics + vacuum",
    "opticsPct": 20.0,
    "thesis": "Diversified vacuum, photonics, and materials supplier with indirect AI photonics exposure."
  },
  {
    "ticker": "VIAV",
    "name": "VIAV",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 36.0,
    "grossMargin": 60.0,
    "operatingMargin": 19.0,
    "market": "US",
    "oneLiner": "Under-discovered test & measurement play; cheapest AI photonics exposure at ~5x sales",
    "catalyst": "AI test demand + margin expansion + restructuring",
    "share": "Optical test",
    "opticsPct": 60.0,
    "thesis": "Under-discovered optical test at 5x sales. 60% GM, 19% OPM."
  },
  {
    "ticker": "3363.TWO",
    "name": "FOCI Fiber Optic Communications",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 12,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 39.0,
    "grossMargin": 18.8,
    "operatingMargin": 0.0,
    "market": "Taiwan",
    "oneLiner": "Sole validated FAU supplier for TSMC COUPE CPO; real positioning but 47x sales on zero earnings. Wait for pullback.",
    "catalyst": "CPO FAU mass production H2 2026 + NT$20B TAM by 2028",
    "share": "Validated COUPE FAU",
    "opticsPct": 90.0,
    "thesis": "Speculative FAU choke point for NVIDIA/TSMC CPO. Real positioning, but the moat is co-design timing rather than proven long-term structural superiority."
  },
  {
    "ticker": "4004.T",
    "name": "Resonac Holdings",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": 24.0,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "#1 epoxy molding compounds but 24% GM = no pricing power. JOINT3 interesting but pre-commercial. Conglomerate dilution.",
    "catalyst": "JOINT3 panel interposer 2026 + NCF 5x expansion + TSMC award",
    "share": "#1 epoxy compounds",
    "opticsPct": 5.0,
    "thesis": "Advanced packaging materials and panel interposer optionality matter to AI hardware, but this is not a photonics-specific bottleneck."
  },
  {
    "ticker": "4062.T",
    "name": "Ibiden",
    "segment": "Context & Adjacent",
    "verdict": "HOLD",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "Real AI substrate bottleneck, wrong layer for this project. Strong business, weak photonics expression.",
    "catalyst": "¥500B AI substrate capex + NVIDIA/AMD co-funding",
    "share": "AI GPU substrates",
    "opticsPct": 0.0,
    "thesis": "Excellent AI substrate franchise, but this is advanced electronic packaging rather than an optical-interconnect bottleneck."
  },
  {
    "ticker": "4063.T",
    "name": "Shin-Etsu Chemical",
    "segment": "Context & Adjacent",
    "verdict": "HOLD",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "World-class semiconductor materials company, but photonics is a rounding error. Context only.",
    "catalyst": "Semi cycle recovery + ¥83B photoresist plant + back-end packaging 2027",
    "share": "#1 silicon wafers",
    "opticsPct": 0.0,
    "thesis": "Best-in-class semiconductor materials franchise whose photonics relevance is too diluted to matter at the stock level."
  },
  {
    "ticker": "5344.T",
    "name": "Maruwa",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": 55.0,
    "operatingMargin": 37.0,
    "market": "Japan",
    "oneLiner": "Global #1 AlN laser submount; 55% GM, 37% OPM, zero debt. AI optical 12.5% of rev but growing fast. Near ATH at 41x P/E.",
    "catalyst": "AlN submount 60%+ share + AI optical 45% OPM + Y100B target",
    "share": "60%+ AlN submount",
    "opticsPct": 12.5,
    "thesis": "Global leader in AlN laser submounts. Photonics is still a minority of revenue, but the optical piece has real bottleneck characteristics."
  },
  {
    "ticker": "5801.T",
    "name": "Furukawa Electric",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": 17.0,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "DFB laser diode maker for SiPh transceivers; real AI story but 92x P/E, 17% GM, 10x stock move. Conglomerate dilution.",
    "catalyst": "DFB laser 500% capacity + SiPh CW laser demand",
    "share": "DFB laser expansion",
    "opticsPct": 5.0,
    "thesis": "There is a real optical-laser story here, but the economics and conglomerate dilution make it a weak public-market expression."
  },
  {
    "ticker": "SITM",
    "name": "SiTime",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 61.0,
    "grossMargin": 56.0,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "MEMS timing monopolist for AI optics. Cheap-but-critical BOM layer, but valuation and deal risk are extreme.",
    "catalyst": "Renesas timing deal close H2 2026 + 1.6T ramp",
    "share": "MEMS timing",
    "opticsPct": 8.0,
    "thesis": "Precision timing sits inside optical modules and AI systems as a cheap but critical function. Strong chokepoint logic, weak current valuation."
  },
  {
    "ticker": "6524.T",
    "name": "Kohoku Kogyo",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 10.0,
    "grossMargin": 43.6,
    "operatingMargin": 28.7,
    "market": "Japan",
    "oneLiner": "Only public pure-play isolator+fiber array co; >50% submarine isolator share, 44% GM, 29% OPM. ~55% lead terminal dilutes.",
    "catalyst": "Q4 +31% acceleration + 800G/1.6T isolator demand + PLZT modulator",
    "share": ">50% submarine isolators",
    "opticsPct": 45.0,
    "thesis": "Niche optical isolator and fiber-array supplier with unusually strong margins and credible passive-component choke point characteristics."
  },
  {
    "ticker": "6890.T",
    "name": "Ferrotec Holdings",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": 28.0,
    "operatingMargin": null,
    "market": "Japan / China",
    "oneLiner": "Real TEC relevance to optics, but the public stock barely expresses it. Tiny optical mix, weak pricing power.",
    "catalyst": "AI transceiver TEC demand + 800G/1.6T ramp",
    "share": "#1 TEC maker",
    "opticsPct": 2.0,
    "thesis": "TEC content matters for transceivers, but the listed vehicle is too diluted and too low-margin to feel like a chokepoint."
  },
  {
    "ticker": "6965.T",
    "name": "Hamamatsu Photonics",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 5,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "90% PMT monopoly but wrong market; zero AI data center exposure. Scientific/medical photonics company.",
    "catalyst": "Medical/semi inspection recovery",
    "share": "PMT monopoly",
    "opticsPct": 0.0,
    "thesis": "Strong photonics company in scientific and medical niches, but not relevant to AI data-center optical chokepoints."
  },
  {
    "ticker": "011790.KS",
    "name": "SKC",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 1.5,
    "grossMargin": -1.0,
    "operatingMargin": null,
    "market": "Korea",
    "oneLiner": "Absolics glass substrate story is real and CHIPS-backed, but the listed parent is financially toxic and pre-revenue on the key asset.",
    "catalyst": "Absolics glass substrate mass production + NVIDIA/AMD design wins",
    "share": "Glass substrates",
    "opticsPct": 0.0,
    "thesis": "Relevant to advanced packaging and future CPO, but this is still a venture-stage substrate bet inside a troubled conglomerate rather than a clean photonics equity."
  },
  {
    "ticker": "6971.T",
    "name": "Kyocera",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 8,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "Japan",
    "oneLiner": "Optical ceramic packaging angle is real, but the stock is mostly a restructuring-heavy conglomerate. Context, not conviction.",
    "catalyst": "Y68B Nagasaki factory + CPO ceramic substrates + restructuring",
    "share": "Optical ceramic pkgs",
    "opticsPct": 2.0,
    "thesis": "Owns relevant ceramic packaging capability, but the optical piece is too small to drive the overall investment case."
  },
  {
    "ticker": "ENTG",
    "name": "Entegris",
    "segment": "Context & Adjacent",
    "verdict": "HOLD",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "High-quality fab consumables business, but generic to all leading-edge fabs. Not a photonics-specific edge.",
    "catalyst": "Semi recovery + content per wafer growth + N2 CMP doubling",
    "share": "Fab materials",
    "opticsPct": 0.0,
    "thesis": "Important semiconductor consumables supplier whose photonics exposure is incidental, not differentiated."
  },
  {
    "ticker": "HIMX",
    "name": "Himax Technologies",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": -8.0,
    "grossMargin": 30.6,
    "operatingMargin": 5.3,
    "market": "Taiwan",
    "oneLiner": "Stealth NVIDIA CPO supplier via WLO nanoimprint for FOCI FAUs; real chokepoint buried in mediocre display driver business.",
    "catalyst": "CPO validation 2026-27 + display recovery + FOCI leading indicator",
    "share": "WLO nanoimprint",
    "opticsPct": 5.0,
    "thesis": "A genuine WLO micro-lens bottleneck may exist inside Himax, but it is still buried inside a cyclical display-driver business."
  },
  {
    "ticker": "KLAC",
    "name": "KLA",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": null,
    "grossMargin": 62.0,
    "operatingMargin": 41.0,
    "market": "US",
    "oneLiner": "Superb process-control monopoly, but photonics is too small inside the franchise to be the point of owning it here.",
    "catalyst": "AI/HBM process control intensity + $950M adv packaging + 2030 $26B target",
    "share": "56-60% process control",
    "opticsPct": 5.0,
    "thesis": "Essential process-control supplier to every serious fab, including SiPh, but the stock is a broad semiconductor-equipment bet rather than a photonics call."
  },
  {
    "ticker": "ONTO",
    "name": "Onto Innovation",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 2.0,
    "grossMargin": 54.6,
    "operatingMargin": 20.9,
    "market": "US",
    "oneLiner": "Interesting optical-metrology share gainer, but still an AI-packaging tool story rather than a photonics bottleneck.",
    "catalyst": "AP >30% growth 2026 + $240M VPA + record backlog",
    "share": "#2 optical metrology",
    "opticsPct": 5.0,
    "thesis": "Real optical-metrology competence, but the investable story remains AI packaging and share gain versus KLA, not photonics chokepoint control."
  },
  {
    "ticker": "688498.SS",
    "name": "Yuanjie Semi",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 20,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 138.5,
    "grossMargin": 56.5,
    "operatingMargin": 35.0,
    "market": "China",
    "oneLiner": "China's InP laser chip monopoly. 56.5% GM, 71.3% DC GM. 554x P/E on STAR Market.",
    "catalyst": "HK IPO filed Mar 2026 + 200G EML sampling",
    "share": "#1 China InP laser chips",
    "opticsPct": 65.0,
    "thesis": "Dominant domestic InP laser chip supplier for entire Chinese transceiver industry. Western alternative to Lumentum."
  },
  {
    "ticker": "688048.SS",
    "name": "Everbright Photonics",
    "segment": "Components & Connectivity",
    "verdict": "WATCH",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 50.0,
    "grossMargin": 30.0,
    "operatingMargin": -10.0,
    "market": "China",
    "oneLiner": "China VCSEL + CW DFB leader, 74% VCSEL efficiency record. Pre-profit at 90x P/S.",
    "catalyst": "VCSEL efficiency record + CW DFB for SiPh",
    "share": "#1 China VCSEL",
    "opticsPct": 80.0,
    "thesis": "Strategic optionality for China laser self-sufficiency. Not yet investable."
  },
  {
    "ticker": "300620.SZ",
    "name": "Adv Fiber Resources",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 16,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 83.0,
    "grossMargin": 40.0,
    "operatingMargin": 18.0,
    "market": "China",
    "oneLiner": "TFLN modulator pioneer. 10x energy efficiency for post-1.6T speeds. 333x P/E.",
    "catalyst": "TFLN modulator platform shift for 1.6T+",
    "share": "TFLN modulator leader",
    "opticsPct": 60.0,
    "thesis": "Potential platform shift from silicon modulators to TFLN. Strongest tech moat of Chinese STAR Market optical names."
  },
  {
    "ticker": "688313.SS",
    "name": "Shijia Photons",
    "segment": "Components & Connectivity",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 65.0,
    "grossMargin": 17.0,
    "operatingMargin": 8.0,
    "market": "China",
    "oneLiner": "China AWG chip leader for DR8/1.6T DWDM + global PLC splitter #1. 17% GM, 145x P/E.",
    "catalyst": "AWG chip demand for 800G/1.6T DWDM transceivers",
    "share": "#1 global PLC splitter",
    "opticsPct": 90.0,
    "thesis": "Only IDM in China for both passive (AWG/PLC) and active (DFB) optical chips."
  },
  {
    "ticker": "688167.SS",
    "name": "Focuslight",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 25.0,
    "grossMargin": 28.0,
    "operatingMargin": -5.0,
    "market": "China",
    "oneLiner": "Chinese WLO/micro-optics for CPO/OCS. Acquired SUSS MicroOptics. 40x P/S, no confirmed CPO customer.",
    "catalyst": "OCS + CPO micro-optics demand",
    "share": "WLO for CPO (unvalidated)",
    "opticsPct": 40.0,
    "thesis": "Real WLO tech but Himax offers same CPO optionality at 1.9x sales with confirmed NVIDIA linkage."
  },
  {
    "ticker": "2345.TW",
    "name": "Accton Technology",
    "segment": "Networking & Systems",
    "verdict": "HOLD",
    "chokepointScore": 13,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 125.0,
    "grossMargin": 18.1,
    "operatingMargin": 12.7,
    "market": "Taiwan",
    "oneLiner": "Edgecore white box switch ODM. +125% rev. First 102.4T switches. Demand multiplier for transceivers.",
    "catalyst": "102.4T switch leadership + Meta/Google hyperscaler wins",
    "share": "#1 white box switch ODM",
    "opticsPct": 15.0,
    "thesis": "Every switch port consumes a transceiver. Demand signal for photonics, not photonics itself."
  },
  {
    "ticker": "TEL",
    "name": "TE Connectivity",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 6.0,
    "grossMargin": 35.7,
    "operatingMargin": 20.9,
    "market": "US",
    "oneLiner": "#1 connector company but weaker AI photonics exposure vs Amphenol. 60% automotive.",
    "catalyst": "DDN +70% YoY + RAM Photonics CPO fiber arrays",
    "share": "#1 global connectors",
    "opticsPct": 5.0,
    "thesis": "Weaker half of connector duopoly for AI photonics. Amphenol has higher AI concentration."
  },
  {
    "ticker": "8249.T",
    "name": "Maruwa",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 17,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 15.0,
    "grossMargin": 54.9,
    "operatingMargin": 37.5,
    "market": "Japan",
    "oneLiner": "60%+ AlN ceramic laser submount share. 55% GM, 37.5% OPM. BUY on pullback.",
    "catalyst": "AI optical projected ~50% of operating profit by FY2028",
    "share": "60%+ AlN laser submounts",
    "opticsPct": 12.5,
    "thesis": "Real photonics chokepoint with exceptional margins. Dramatically better than Kyocera."
  },
  {
    "ticker": "2802.T",
    "name": "Ajinomoto",
    "segment": "Materials & Substrates",
    "verdict": "HOLD",
    "chokepointScore": 22,
    "chokepointTier": "Monopoly Chokepoint",
    "revenueGrowth": 4.0,
    "grossMargin": 35.0,
    "operatingMargin": 10.0,
    "market": "Japan",
    "oneLiner": "95% ABF film monopoly. Every FC-BGA substrate needs it. Palliser activist catalyst.",
    "catalyst": "Palliser demanding 30% ABF price hike + standalone disclosure",
    "share": "~95% ABF film",
    "opticsPct": 1.0,
    "thesis": "Semiconductor chokepoint, not photonics-specific. ABF film is in every GPU/CPU substrate."
  },
  {
    "ticker": "CAMT",
    "name": "Camtek",
    "segment": "Equipment",
    "verdict": "HOLD",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 16.0,
    "grossMargin": 50.5,
    "operatingMargin": 25.8,
    "market": "Israel",
    "oneLiner": "Advanced packaging inspection leader with ~50% AI/HPC mix. Real HBM chokepoint, only indirect to photonics.",
    "catalyst": "HBM4 Hawk ramp + CoWoS expansion + double-digit 2026 growth",
    "share": "HBM / advanced packaging inspection",
    "opticsPct": 6.0,
    "thesis": "Niche AP inspection leader with the highest AI/HPC concentration in inspection, but not a photonics-specific bottleneck."
  },
  {
    "ticker": "6754.T",
    "name": "Anritsu",
    "segment": "Test & Infrastructure",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 2.7,
    "grossMargin": 48.7,
    "operatingMargin": 10.7,
    "market": "Japan",
    "oneLiner": "Production-line optical test standard via MP2110A BERTWave. Real niche choke point, but only ~25% optical mix.",
    "catalyst": "1.6T production test ramp + 60 GHz MP2110A + inventory normalization",
    "share": "Production optical test",
    "opticsPct": 25.0,
    "thesis": "The de facto production-test standard for optical transceivers, complementary to Keysight's R&D test leadership."
  },
  {
    "ticker": "ADTN",
    "name": "Adtran Holdings",
    "segment": "Networking & Systems",
    "verdict": "AVOID",
    "chokepointScore": 8,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 17.0,
    "grossMargin": 38.3,
    "operatingMargin": 1.7,
    "market": "US / Germany",
    "oneLiner": "Subscale optical networking vendor with ADVA assets, but no hyperscaler AI edge and no chokepoint position.",
    "catalyst": "800G coherent upgrade cycle + revenue recovery to $1.2B",
    "share": "Subscale optical transport",
    "opticsPct": 35.0,
    "thesis": "Recovering optics vendor, but still a distant 4th-tier player behind Ciena, Nokia/Infinera, and Cisco/Acacia."
  },
  {
    "ticker": "2308.TW",
    "name": "Delta Electronics",
    "segment": "Networking & Systems",
    "verdict": "AVOID",
    "chokepointScore": 7,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": 32.0,
    "grossMargin": 34.3,
    "operatingMargin": 16.4,
    "market": "Taiwan",
    "oneLiner": "Major AI power and cooling winner with a real but tiny optical sidecar through AGEMA switches and Source Photonics demos.",
    "catalyst": "AI power/cooling demand + AGEMA 1.6T switch",
    "share": "Optical / networking sidecar",
    "opticsPct": 2.0,
    "thesis": "A data-center infrastructure winner, not a photonics chokepoint. Optical exposure is real but immaterial inside a giant industrial."
  },
  {
    "ticker": "MYCR.ST",
    "name": "Mycronic",
    "segment": "Assembly & Packaging",
    "verdict": "HOLD",
    "chokepointScore": 15,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": 12.0,
    "grossMargin": 53.0,
    "operatingMargin": 28.0,
    "market": "Sweden",
    "oneLiner": "Dual photonics angle through laser mask writers and MRSI die bonders, but still a niche hold rather than a core bottleneck.",
    "catalyst": "SiPh mask writer demand + MRSI photonic die bonders for CPO ramp",
    "share": "Mask writers + MRSI die bonding",
    "opticsPct": 18.0,
    "thesis": "Solid niche economics and real photonics tools, but not singular enough to qualify as a top-tier chokepoint."
  },
  {
    "ticker": "ATS.VI",
    "name": "AT&S",
    "segment": "Assembly & Packaging",
    "verdict": "AVOID",
    "chokepointScore": 14,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": 9.5,
    "operatingMargin": null,
    "market": "Austria",
    "oneLiner": "European substrate player with genuine glass-substrate and photonics R&D, but weak economics and no chokepoint power today.",
    "catalyst": "EU Chips Act subsidy + glass substrate and photonics packaging R&D",
    "share": "IC substrates / packaging",
    "opticsPct": 5.0,
    "thesis": "Interesting EU strategic substrate angle, but low margins and early-stage photonics work make it non-actionable for this map."
  },
  {
    "ticker": "300570.SZ",
    "name": "Taichen / MPO Connector Vendor",
    "segment": "Fiber & Connectors",
    "verdict": "AVOID",
    "chokepointScore": 11,
    "chokepointTier": "Oligopoly with Moat",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "MPO connector beneficiary for 800G/1.6T, but standardized form factors and crowded competition cap moat quality.",
    "catalyst": "800G / 1.6T MPO connector volume ramp for Microsoft and Amazon supply chains",
    "share": "MPO connectors",
    "opticsPct": 40.0,
    "thesis": "Real beneficiary of high-speed optical connector volume, but too standardized and too competitive to count as a choke point."
  },
  {
    "ticker": "ROG",
    "name": "Rogers Corp",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 10,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": 31.7,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "High-frequency laminates and RF materials matter to data infrastructure, but this is not an optical transceiver bottleneck.",
    "catalyst": "Data center design wins + ADAS growth",
    "share": "High-frequency laminates",
    "opticsPct": 5.0,
    "thesis": "Relevant as infrastructure-adjacent materials exposure, but not a photonics chokepoint and not differentiated enough for the core map."
  },
  {
    "ticker": "6834.T",
    "name": "Seikoh Giken",
    "segment": "Fiber & Connectors",
    "verdict": "HOLD",
    "chokepointScore": 18,
    "chokepointTier": "Duopoly Chokepoint",
    "revenueGrowth": 35.0,
    "grossMargin": 43.3,
    "operatingMargin": 26.0,
    "market": "Japan",
    "oneLiner": "World #1 ceramic ferrule and polishing-equipment supplier. Hidden toll collector on AI optical connector density.",
    "catalyst": "AI fabric densification 20-40x connectors/rack + 800G/1.6T ramp",
    "share": "#1 ceramic ferrules",
    "opticsPct": 70.0,
    "thesis": "A real connector-layer chokepoint with a razor/blade model, but the current valuation already prices in years of connector growth."
  },
  {
    "ticker": "688027.SS",
    "name": "QuantumCTek",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 5,
    "chokepointTier": "Commodity / Indirect",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "China",
    "oneLiner": "Largest QKD company, but its photonic components are quantum-only and not relevant to AI data-center optics.",
    "catalyst": "QKD market growth + China quantum national program",
    "share": "Quantum-only optics",
    "opticsPct": 15.0,
    "thesis": "Real photonics technology, wrong end-market. Included for coverage completeness, not because it belongs in the AI optics choke-point set."
  },
  {
    "ticker": "AEVA",
    "name": "Aeva Technologies",
    "segment": "Context & Adjacent",
    "verdict": "AVOID",
    "chokepointScore": 8,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "InP LiDAR company pivoting to data-center SOAs. Real tech, but still pre-qualification and far from a proven optical supplier.",
    "catalyst": "SOA for CPO announced Jan 2026 + InP fab",
    "share": "Emerging SOA pivot",
    "opticsPct": 20.0,
    "thesis": "Interesting technology and a legitimate DC-SOA angle, but far too early and too cash-burn-heavy to count as a current choke point."
  },
  {
    "ticker": "LWLG",
    "name": "Lightwave Logic",
    "segment": "Components & Connectivity",
    "verdict": "AVOID",
    "chokepointScore": 8,
    "chokepointTier": "Competitive / Linked",
    "revenueGrowth": null,
    "grossMargin": null,
    "operatingMargin": null,
    "market": "US",
    "oneLiner": "EO polymer for SiPh modulators. Pre-revenue ($237K). GF PDK integration. 6700x P/S.",
    "catalyst": "GF + Tower PDK integration + Stage 3 programs",
    "share": "Pre-commercial",
    "opticsPct": 100.0,
    "thesis": "Speculative pre-revenue materials company. Real tech but $1.6B cap on $237K revenue."
  }
];
